Region: ap-southeast-1
Image:
  Os: ubuntu2204
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-00b4914f9ad4bb073
    AdditionalSecurityGroups:
    - sg-0640550592de716d8
  Ssh:
    KeyName: ansible-pem
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2micro
      Instances:
      - InstanceType: t2.micro
      MinCount: 1
      MaxCount: 8
    Networking:
      SubnetIds:
      - subnet-015434231a4bce6ce
      AdditionalSecurityGroups:
      - sg-0640550592de716d8
    Iam:
      S3Access:
        - BucketName: gcp-slurm-10012024
          EnableWriteAccess: true

  SlurmSettings:
    QueueUpdateStrategy: TERMINATE
    CustomSlurmSettings:
      - JobRequeue: 0

SharedStorage:
  - MountDir: /fsx
    Name: t2-micro-fsx
    StorageType: FsxLustre
    FsxLustreSettings:
        FileSystemId: fs-0886ceded021519e4

  # - MountDir: string
  #   Name: string
  #   StorageType: Efs
  #   EfsSettings:
  #     Encrypted: boolean
  #     KmsKeyId: string
  #     EncryptionInTransit: boolean
  #     IamAuthorization: boolean
  #     PerformanceMode: string
  #     ThroughputMode: string
  #     ProvisionedThroughput: integer
  #     FileSystemId: string
  #     DeletionPolicy: string
  #     AccessPointId: string